spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cs25?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true

  # JPA
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true

  # Oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "756213224447-v8cv3ud5haopoovjl0hm8q2u12nlp1en.apps.googleusercontent.com"
            client-secret: "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"
            redirect-uri: "http://localhost:3000/api/v1/auth/google/callback"
          kakao:
            client-id: "cd1ae42f3f91320e199f971e344c4034"
            client-secret: "52dRbK3hLPXKF5laS1JbwdEjMZKP79GS"
            redirect-uri: "http://localhost:3000/api/v1/auth/kakao/callback"
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - profile_nickname
              - profile_image

          naver:
            client-id: "X8XoZlM8E5IHLQ01OvDf"
            client-secret: "LDUncRXZAi"
            redirect-uri: "http://localhost:3000/api/v1/auth/naver/callback"
            client-name: Naver
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - name
              - profile
        provider:
          google:
            authorization-uri: "https://accounts.google.com/o/oauth2/v2/auth"
            token-uri: "https://oauth2.googleapis.com/token"
            user-info-uri: "https://www.googleapis.com/oauth2/v1/userinfo"
          kakao:
            authorization-uri: "https://kauth.kakao.com/oauth/authorize"
            token-uri: "https://kauth.kakao.com/oauth/token"
            user-info-uri: "https://kapi.kakao.com/v2/user/me"
          naver:
            authorization-uri: "https://nid.naver.com/oauth2.0/authorize"
            token-uri: "https://nid.naver.com/oauth2.0/token"
            user-info-uri: "https://openapi.naver.com/v1/nid/me"


server:
  port: 8080

jwt:
  secret: "5873a7d2433694a23cd0d559d72b8b3289075de264ef032c33760c2179e851d7e0cba2f9d52435fb8353f8caffeb5957599302252282b04886bcdce812c900b9"
  accessExpiredMs: 3600000
  refreshExpiredMs: 4200000000

---